# -*- coding: utf-8 -*-
"""classify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0Co5k90E-k96A3z-r5CGVAsIHPgZqlN
"""

# -*- coding:utf-8 -*-
import torch
import torch.nn.functional as F
import numpy as np
import os
from tqdm import tqdm

from .model import MLP
from .loss import loss_coteaching


# ---------------- Hyper Parameters ---------------- #
batch_size = 128
learning_rate = 1e-3
epochs = 100
num_gradual = 10
forget_rate = 0.1
exponent = 1

rate_schedule = np.ones(epochs) * forget_rate
rate_schedule[:num_gradual] = np.linspace(
    0, forget_rate ** exponent, num_gradual
)


# ---------------- Accuracy ---------------- #
def accuracy(logit, target):
    output = F.softmax(logit, dim=1)
    _, pred = output.topk(1, 1, True, True)
    pred = pred.t()

    correct = pred.eq(target.view(1, -1).expand_as(pred))
    correct_k = correct[:1].reshape(-1).float().sum(0)

    return correct_k.mul_(100.0 / target.size(0))


# ---------------- Train ---------------- #
def train(train_loader, epoch, model1, optimizer1, model2, optimizer2, device):

    for data_labels in train_loader:

        data_labels = data_labels.numpy()

        feats = torch.tensor(data_labels[:, :-1], dtype=torch.float32)
        labels = torch.tensor(data_labels[:, -1], dtype=torch.long)

        if device is not None:
            feats = feats.to(device)
            labels = labels.to(device)

        logits1 = model1(feats)
        logits2 = model2(feats)

        loss_1, loss_2 = loss_coteaching(
            logits1, logits2, labels, rate_schedule[epoch]
        )

        optimizer1.zero_grad()
        loss_1.backward()
        optimizer1.step()

        optimizer2.zero_grad()
        loss_2.backward()
        optimizer2.step()


# ---------------- Predict (returns probabilities) ---------------- #
def predict(test_loader, model, device):

    all_probs = []

    for data in test_loader:

        feats = data.clone().detach().float()

        if device is not None:
            feats = feats.to(device)

        logits = model(feats)
        outputs = F.softmax(logits, dim=1)

        all_probs.append(outputs[:, 1].detach().cpu().numpy())

    probs = np.concatenate(all_probs, axis=0)

    print("\n📊 Prediction Stats:")
    print("Avg probability:", probs.mean())
    print("Max probability:", probs.max())

    return probs


# ---------------- Threshold Tuning ---------------- #
def evaluate_thresholds(probs, test_label):

    best_f1 = 0
    best_alpha = 0.5

    print("\n🔍 Threshold Tuning:")

    for alpha in np.arange(0.01, 0.5, 0.02):

        preds = (probs > alpha).astype(int)

        scores = np.zeros((2, 2))

        for label, pred in zip(test_label, preds):
            scores[int(label), int(pred)] += 1

        TP = scores[1, 1]
        FP = scores[0, 1]
        TN = scores[0, 0]
        FN = scores[1, 0]

        Recall = TP / (TP + FN + 1e-8)
        Precision = TP / (TP + FP + 1e-8)
        F1 = 2 * Recall * Precision / (Recall + Precision + 1e-8)

        print(f"Alpha={alpha:.2f} | Recall={Recall:.3f} Precision={Precision:.3f} F1={F1:.3f}")

        if F1 > best_f1:
            best_f1 = F1
            best_alpha = alpha

    print("\n🔥 BEST ALPHA:", best_alpha, "F1:", best_f1)

    return best_alpha


# ---------------- Main ---------------- #
def main(feat_dir, model_dir, result_dir, TRAIN, cuda_device, parallel=5):

    # ✅ SAFE DEVICE HANDLING
    device = torch.device("cuda" if (cuda_device and torch.cuda.is_available()) else "cpu")

    # ---------------- Load Data ---------------- #
    be = np.load(os.path.join(feat_dir, "be_corrected.npy"))[:, :32]
    ma = np.load(os.path.join(feat_dir, "ma_corrected.npy"))[:, :32]

    be_shape = be.shape[0]
    ma_shape = ma.shape[0]

    for index in range(parallel):

        be_gen = np.load(
            os.path.join(feat_dir, f"be_{TRAIN}_generated_GAN_{index}.npy")
        )
        ma_gen1 = np.load(
            os.path.join(feat_dir, f"ma_{TRAIN}_generated_GAN_1_{index}.npy")
        )
        ma_gen2 = np.load(
            os.path.join(feat_dir, f"ma_{TRAIN}_generated_GAN_2_{index}.npy")
        )

        np.random.shuffle(be_gen)
        np.random.shuffle(ma_gen1)
        np.random.shuffle(ma_gen2)

        be = np.concatenate(
            [be, be_gen[: be_shape // parallel]], axis=0
        )

        ma = np.concatenate(
            [
                ma,
                ma_gen1[: ma_shape // parallel],
                ma_gen2[: ma_shape // parallel],
            ],
            axis=0,
        )

    print("\n📊 Train shape:", be.shape, ma.shape)
    print("Final Benign:", len(be))
    print("Final Malicious:", len(ma))
    print("Malicious Ratio:", len(ma)/(len(be)+len(ma)))
    train_data = np.concatenate([be, ma], axis=0)
    train_label = np.concatenate(
        [np.zeros(len(be)), np.ones(len(ma))], axis=0
    )

    train_dataset = np.concatenate(
        (train_data, train_label[:, None]), axis=1
    )

    test_data_label = np.load(os.path.join(feat_dir, "test.npy"))
    test_data = test_data_label[:, :32]
    test_label = test_data_label[:, -1]

    # ---------------- DataLoader ---------------- #
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True
    )

    test_loader = torch.utils.data.DataLoader(
        test_data, batch_size=batch_size, shuffle=False
    )

    # ---------------- Models ---------------- #
    print("\n🚀 Building model...")

    mlp1 = MLP(input_size=32, hiddens=[16, 8], output_size=2, device=device)
    mlp2 = MLP(input_size=32, hiddens=[16, 8], output_size=2, device=device)

    mlp1 = mlp1.to(device)
    mlp2 = mlp2.to(device)

    optimizer1 = torch.optim.Adam(mlp1.parameters(), lr=learning_rate)
    optimizer2 = torch.optim.Adam(mlp2.parameters(), lr=learning_rate)

    # ---------------- Training ---------------- #
    mlp1.train()
    mlp2.train()

    for epoch in tqdm(range(epochs)):
        train(
            train_loader, epoch,
            mlp1, optimizer1,
            mlp2, optimizer2,
            device
        )

    # ---------------- Testing ---------------- #
    mlp1.eval()

    probs = predict(test_loader, mlp1, device)

    # 🔥 AUTO THRESHOLD SELECTION
    best_alpha = evaluate_thresholds(probs, test_label)

    preds = (probs > best_alpha).astype(int)

    np.save(os.path.join(result_dir, "prediction.npy"), preds)

    # ---------------- Metrics ---------------- #
    scores = np.zeros((2, 2))

    for label, pred in zip(test_label, preds):
        scores[int(label), int(pred)] += 1

    TP = scores[1, 1]
    FP = scores[0, 1]
    TN = scores[0, 0]
    FN = scores[1, 0]

    Accuracy = (TP + TN) / (TP + TN + FP + FN + 1e-8)
    Recall = TP / (TP + FN + 1e-8)
    Precision = TP / (TP + FP + 1e-8)
    F1score = 2 * Recall * Precision / (Recall + Precision + 1e-8)

    print("\n📊 FINAL RESULTS")
    print("Recall:", Recall)
    print("Precision:", Precision)
    print("F1:", F1score)
    print("Accuracy:", Accuracy)

    os.makedirs("../data/result", exist_ok=True)

    with open("../data/result/detection_result.txt", "w") as fp:
        fp.write(
            f"Testing data: Benign/Malicious = {(TN + FP)}/{(TP + FN)}\n"
        )
        fp.write(
            f"Recall: {Recall:.2f}, Precision: {Precision:.2f}, F1: {F1score:.2f}\n"
        )
        fp.write(f"Acc: {Accuracy:.2f}\n")

    torch.save(mlp1, os.path.join(model_dir, "Detection_Model.pkl"))